name: Build and Release Systemd Sysext Images

on:
  push:
    # tags:
    #   - 'latest'
    #   - '[0-9]+'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          path: bakery

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install prerequisites
        run: |
          set -euxo pipefail
          sudo apt update -qq && sudo apt install -yqq \
            curl \
            jq \
            squashfs-tools \
            xz-utils \
            gawk

      - name: Build release artifacts
        run: |
          pushd bakery
          REPO=${{ github.repository }} ./bake_flatcar_image.sh sysext/targetcli/manifest.yaml

      - name: Create a new latest release with artifacts
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          body_path: bakery/Release.md
          files: |
            output/targetcli.sysext
            output/SHA256SUMS

      - name: Upload targetcli artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            output/targetcli*.raw
