name: Build and Release Systemd Sysext Images

on:
  push:
    tags:
      # - 'latest'
      # - '[0-9]+'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      # Checkout the sources
      - uses: actions/checkout@v4

      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Install prerequisites
      - name: Install prerequisites
        run: |
          set -euxo pipefail
          sudo apt update -qq && sudo apt install -yqq \
            curl \
            jq \
            squashfs-tools \
            xz-utils \
            gawk \
            bzip2 \
            gpg

      # Build the sysext image
      - name: Build Sysext Image
        run: |
          pushd sysext/targetcli
          ./bake_flatcar_image.sh --fetch --install_to root:/opt/extensions/ manifest.yaml
          popd

      # Create a new latest release with artifacts
      - name: Create a new latest release with artifacts
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          body_path: sysext/targetcli/Release.md
          files: |
            output/targetcli.sysext
            output/SHA256SUMS

      # Optionally, upload additional artifacts
      - name: Upload targetcli artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            output/targetcli*.raw
